version: 2.1

jobs:
  build:
    macos:
      xcode: 12.5.1  # Specify the Xcode version you need for iOS
    resource_class: macos.medium  # Use a supported macOS resource class
    steps:
      - checkout
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run:
          name: Install Node
          command: brew install node
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Install Watchman
          command: brew install watchman
      - run:
          name: Install React Native CLI
          command: npm install -g react-native-cli
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - build
